name: Build TUMA APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build APK
        uses: bdarmy/buildozer-action@v1
        with:
          buildozer_version: master
          command: buildozer android debug