name: Build TUMA APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: bdarmy/buildozer-action@v1
        with:
          buildozer_version: master
          command: buildozer android debug
          workdir: .
          buildozer_flags: --accept-licenses